src/api/logsAPI.ts, src/api/userAPI.ts, src/components/Card/TimeLogCard.tsx, src/components/layout/HomeContents.tsx, src/pages/Main.tsx, src/routes/AppRouter.tsx
=> Feat: API response 값 변경(#13)

public/index.html, public/manifest.json
[-] public/index.html의 오타를 수정하였습니다.
[-] public/manifest.json의 오타를 수정하였습니다.
=> Fix: #23 타이틀 오타 수정

src/App.tsx, src/components/Card/Card.tsx, src/components/Card/TimeLogCard.tsx, src/components/common/Loading.tsx, src/styles/components/Card/CardContents.module.css, src/styles/components/Loading.module.css, src/styles/pages/Main.module.css, src/utils/hooks/queries/useMainQuery.ts, src/utils/hooks/queries/useMonthTimeLogsQuery.ts
-데이터 로딩 시 서스펜스의 fallback 컴포넌트를 보여주게 처리 하였습니다.
=> Feat: 로딩시 서스펜스 처리 (#31)

src/pages/Home.tsx
- 변경 전 기존의 주소창에 main을 추가하는 부분을 origin으로 변경하였습니다.
=> Fix: 로그인 시 리다이렉트 고침 (#30)

src/stores/monthlog.ts
선택한 날짜에 오늘 날짜의 로그가 섞이는 현상이 있어서 핫픽스했습니다.
=> Hotfix: 오늘 날짜가 아닌 다른 날짜 선택시에도 오늘날짜의 로그가 보이는 현상

src/stores/home.ts, src/stores/monthlog.ts, src/views/HomeView.vue
home에서 누적 일, 누적 월 시간에 대한 값을 perMonth 데이터에서 AccumulationTime 으로 변경하였습니다.
Closes #52
=> FIX: home 뷰에서 사용하는 api 교체 #52

src/views/HomeView.vue
월 로그 데이터를 가져올 때,
기존의 방식의 경우, 최신 데이터인지 확인을 하여 월 데이터를 가지고 올 것인지, 아니면 오늘 하루의 데이터를 가지고 올 것인지에 대해 조건 처리를 하였습니다. 해당 방식이 api 요청은 덜하고, 빠른 방식이었으나, 조건이 복잡함에 따라 오류가 일부 있었는데, 이번 백엔드 성능 업데이트에 따라 불필요해진 상황이되어 해당 방식을 이번 달인 경우엔 월 로그 전체를 갱신하는 방식으로 다시 롤백했습니다.
=> 월 로그 데이터를 가져오는 조건부 수정

src/components/common/MenuBar.vue, src/views/HomeView.vue
모바일에서 홈 뷰에 배경이 스크롤 여부에 따라 크기가 변경되는 UX 개선을 위한 pr입니다. 100% -> 100vh로 변경해서 모바일에서 어떻게 나오는지 확인을 하기 위한 pr입니다.
=> 모바일에서 홈 뷰에 배경이 스크롤 여부에 따라 크기가 변경되는 UX 개선#63

src/views/HomeView.vue
홈 뷰 배경 이미지 스크롤에 따른 크기 변경되는 부분을 해결하기 위한 PR입니다.
=> 홈 뷰 배경 이미지 스크롤에 따른 크기 변경 #63

src/views/HomeView.vue
=> 홈 뷰 배경 이미지 스크롤에 따른 크기 변경 리셋

src/components/common/HeaderBar.vue, src/views/HomeView.vue
온라인인 경우, 
스크롤 시 헤더가 안보이는 부분 수정
배경 꿀렁거리는 부분 수정
조치했습니다.
=> 온라인인 경우, 배경 고정 및 헤더 배경 추가

src/stores/monthlog.ts
logsContainer length 조건식 추가로 인한 버그 핫픽스 입니다.
=> BUG: logsContainer length 이슈

src/stores/monthlog.ts
캘린더 뷰에서 있을때 nav bar의 캘린더 뷰 버튼을 한번 더 클릭 시 
데이터 값이 갱신될 수 있도록 기능 추가했습니다.
=> [FE] FEAT: 캘린더에서 캘린더 버튼 누를 시 새로고침되도록 기능 추가

package-lock.json, package.json, src/api/logsAPI.ts, src/api/userAPI.ts, src/components/calendar/AccMonth.vue, src/components/common/DefaultModal.vue, src/components/home/FoldCardCompact.vue, src/components/home/UserNumSection.vue, src/components/icons/IconExclamationMark.vue, src/stores/home.ts, src/stores/monthlog.ts, src/types/User.ts, src/types/logs.ts, src/views/HomeView.vue, tsconfig.vitest.json
type check error가 나면서, action이 안돌아서 수정해서 올립니다.
=> [FE] FIX: 배포 작업을 위한 type check #75

package-lock.json, package.json, src/components/home/UserNumSection.vue, src/views/HomeView.vue
github action이 type check error로 안돌아서 수정합니다.
=> [FE] FIX: type-check 수정

src/components/common/LoadingAnimation.vue, src/components/home/FoldCard.vue, src/components/home/FoldCardCompact.vue, src/stores/home.ts, src/views/HomeView.vue
로딩 애니메이션이 자연스럽게 변경되었습니다.
홈에서 새로고침 시 시간 값들에 로딩 애니메이션이 나오도록 변경했습니다.
=> [FE] FIX: home 로딩 시 로딩 애니메이션 보여주기 #75

src/stores/home.ts, src/views/HomeView.vue
안내 메시지를 띄우는 타이밍을 MainInfo api 가 완료되는 시점으로 변경하기 위해서 isMainInfoLoading 변수를 따로 만들어서 사용합니다.
=> [FE] FEAT: isMainInfoLoading 추가 #75

src/stores/monthlog.ts
해당 관련 코드인 calcOptions 코드를 수정했습니다.
=> [FE] FIX: 월선택 제대로 안나오는 부분 수정 #83

src/api/cookie/cookies.ts
dev에서 쿠키가 삭제 안되어, 정확한 도메인을 적어서 테스트합니다.
=> [FE] FIX: removeCookie 삭제 도메인 변경 #86

index.html
=> [FE] FEAT: GA 적용

index.html, package-lock.json, package.json, src/components/Login/LoginButton.vue, src/components/calendar/AccMonth.vue, src/main.ts
=> [FE] FEAT: ga, na 추가 및 event추가 #96

index.html, package-lock.json, package.json, src/components/Login/LoginButton.vue, src/components/calendar/AccMonth.vue, src/main.ts
dev to main 입니다.
기존의 GA 스크립트 대신, vue-gtag를 사용하는 방식으로 변경했습니다.
=> Develop to master

.github/workflows/s3_deploy_master.yml, index.html
GA 적용을 위한 CICD 파일 수정 
dev to main
=> [FE] deploy master yml 파일 수정

index.html
=> [FE] FIX: NA 코드 삭제
